// builds_webapps/Web_Connect_App/Jenkinsfile
@Library('phyllo-shared-lib') _

pipeline {
    agent any

    environment {
        BUCKET_NAME = "connect-app-dev-bucket"
    }

    stages {
        stage('Checkout SCM') {
            steps { checkout scm }
        }

        stage('Environment config') {
            steps {
                echo "Setting up environment for Web_Connect_App..."
            }
        }

        stage('Install Packages') {
            steps {
                sh 'npm install || echo "no package.json"'
            }
        }

        stage('Test and Build') {
            steps {
                sh 'npm test || echo "no tests"'
                buildApp()
            }
        }

        stage('Deploy to Production') {
            steps {
                deployApp(env.BUCKET_NAME)
            }
        }
    }
}
