// builds_webapps/Web_Social_Guard/Jenkinsfile
@Library('phyllo-shared-lib') _

pipeline {
    agent any

    environment {
        BUCKET_NAME = "social-guard-dev-bucket"
    }

    stages {
        stage('Checkout SCM') {
            steps { checkout scm }
        }

        stage('Environment config') {
            steps {
                echo "Setting up environment for Web_Social_Guard..."
            }
        }

        stage('Install Packages') {
            steps {
                sh 'npm install || echo "no package.json"'
            }
        }

        stage('Create Build Artifacts') {
            steps {
                buildApp()
            }
        }

        stage('Deploy') {
            steps {
                deployApp(env.BUCKET_NAME)
            }
        }
    }
}
